    -- Crear base de datos (ajusta el nombre si lo deseas)
    CREATE DATABASE IF NOT EXISTS Diccionario
      DEFAULT CHARACTER SET utf8mb4
      COLLATE utf8mb4_spanish_ci;

    USE Diccionario;

    -- Crear tabla
    CREATE TABLE IF NOT EXISTS TERMS (
      Id INT NOT NULL AUTO_INCREMENT,
      Esp VARCHAR(70) NOT NULL,
      Eng VARCHAR(70) NOT NULL,
      PRIMARY KEY (Id),
      UNIQUE KEY uq_terms_esp_eng (Esp, Eng)
    ) ENGINE=InnoDB
      DEFAULT CHARSET=utf8mb4
      COLLATE=utf8mb4_spanish_ci;

    INSERT INTO TERMS (Esp, Eng) VALUES
    ('Algoritmo','Algorithm'),
    ('Compilador','Compiler'),
    ('Intérprete','Interpreter'),
    ('Depuración','Debugging'),
    ('Registro','Logging'),
    ('Trazas','Tracing'),
    ('Fallo','Failure'),
    ('Excepción','Exception'),
    ('Controlador','Controller'),
    ('Servicio','Service'),
    ('Repositorio','Repository'),
    ('Entidad','Entity'),
    ('Interfaz','Interface'),
    ('Implementación','Implementation'),
    ('Biblioteca','Library'),
    ('Marco de trabajo','Framework'),
    ('Paquete','Package'),
    ('Módulo','Module'),
    ('Dependencia','Dependency'),
    ('Gestor de paquetes','Package manager'),
    ('Semántica','Semantics'),
    ('Sintaxis','Syntax'),
    ('Compilación','Compilation'),
    ('Despliegue','Deployment'),
    ('Integración continua','Continuous integration'),
    ('Entrega continua','Continuous delivery'),
    ('Canalización','Pipeline'),
    ('Versionado','Versioning'),
    ('Control de versiones','Version control'),
    ('Rama','Branch'),
    ('Etiqueta','Tag'),
    ('Confirmación','Commit'),
    ('Fusión','Merge'),
    ('Conflicto','Conflict'),
    ('Auditoría','Audit'),
    ('Revisión','Review'),
    ('Aprovisionamiento','Provisioning'),
    ('Orquestación','Orchestration'),
    ('Contenedor','Container'),
    ('Imagen','Image'),
    ('Virtualización','Virtualization'),
    ('Monitorización','Monitoring'),
    ('Observabilidad','Observability'),
    ('Métrica','Metric'),
    ('Alerta','Alert'),
    ('Panel','Dashboard'),
    ('Registro de eventos','Event log'),
    ('Cola de mensajes','Message queue'),
    ('Correlación','Correlation'),
    ('Latencia','Latency'),
    ('Rendimiento','Performance'),
    ('Escalabilidad','Scalability'),
    ('Disponibilidad','Availability'),
    ('Tolerancia a fallos','Fault tolerance'),
    ('Alta disponibilidad','High availability'),
    ('Equilibrado de carga','Load balancing'),
    ('Caché','Cache'),
    ('Almacenamiento','Storage'),
    ('Disco','Disk'),
    ('Memoria','Memory'),
    ('Procesador','CPU'),
    ('Hilo','Thread'),
    ('Proceso','Process'),
    ('Concurrencia','Concurrency'),
    ('Paralelismo','Parallelism'),
    ('Bloqueo','Lock'),
    ('Interbloqueo','Deadlock'),
    ('Región crítica','Critical section'),
    ('Sincronización','Synchronization'),
    ('Semáforo','Semaphore'),
    ('Exclusión mutua','Mutual exclusion'),
    ('No bloqueante','Non-blocking'),
    ('Asíncrono','Asynchronous'),
    ('Promesa','Promise'),
    ('Devolución de llamada','Callback'),
    ('Interfaz de línea de comandos','Command-line interface'),
    ('Punto final','Endpoint'),
    ('Dirección web','URL'),
    ('Solicitud','Request'),
    ('Respuesta','Response'),
    ('Estado','Status'),
    ('Autenticación','Authentication'),
    ('Autorización','Authorization'),
    ('Credencial','Token'),
    ('Sesión','Session'),
    ('Cabecera','Header'),
    ('Cuerpo','Body'),
    ('Cifrado','Encryption'),
    ('Resumen criptográfico','Hash'),
    ('Firma digital','Digital signature'),
    ('Certificado','Certificate'),
    ('Clave pública','Public key'),
    ('Clave privada','Private key'),
    ('Sal','Salt'),
    ('Semilla','Seed'),
    ('Aleatoriedad','Randomness'),
    ('Normalización','Normalization'),
    ('Desnormalización','Denormalization'),
    ('Integridad referencial','Referential integrity'),
    ('Serialización','Serialization');

